baseURL = "http://yokossa.com"
languageCode = "en-us"
title = "Yokossa!"
theme = "hugo-theme-cleanwhite"


name = "Clean White"
license = "Apache"
licenselink = "https://github.com/zhaohuabing/hugo-theme-cleanwhite/blob/master/LICENSE"
description = "A clean, elegant blog theme for hugo"
homepage = "https://github.com/zhaohuabing/hugo-theme-cleanwhite"
tags = [ "minimal", "responsive", "blog","light", "clean", "search"]
features = ["disqus", "site search", "responsive", "google analytics", "side bar"]
min_version = 0.10

[author]
  name = "Hello World"
  homepage = "https://github.com/pipernet"

# If porting an existing theme
[original]
  name = "Yokossa"
  homepage = "https://Yokossa.com"